### ISSUE TITLE
[Tracker] 2.0 release

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#414]
The 2.0 release contains the upstream 3.0 changes, mostly pallet macro refactors.
It will also include initial smart contract integration work.

A rough plan to integrate the changes would be:

- [x] Update with 1.5.0
- [x] Review Generic Asset locks/reserve behaviour (see NFT auctions)
- [x] Re-benchmark GA
- [x] Update deps to build from a substrate commit
    - [ ] close #386 
- [x] Review Treasury Config
