### ISSUE TITLE
Rewrite FeeExchange

### ISSUE THREAD

**Issue by jordy25519** [cennznet/cennznet#85]
Provide seamless fee payment in multiple currencies by converting the requested asset into
the network spending token.

This is a tracking issue.
- [x] Add transaction-payment module: https://github.com/cennznet/cennznet/issues/86
- [x] Add BuyFeeAsset trait: https://github.com/cennznet/cennznet/issues/87
- [x] Add FeeExchange and pay with CENNZX: https://github.com/cennznet/cennznet/issues/88

**Comment by jordy25519** [comment]
Closed by #99
